#define XBOX_A 0
#define XBOX_B 1
#define XBOX_X 2
#define XBOX_Y 3
#define XBOX_LB 4
#define XBOX_RB 5
#define XBOX_BACK 6
#define XBOX_START 7
#define XBOX_GUIDE 8
#define XBOX_LSTICK_PUSH 9
#define XBOX_RSTICK_PUSH 10

#define XBOX_LSTICK_X 0
#define XBOX_LSTICK_Y 1
#define XBOX_LTRIGGER 2
#define XBOX_RSTICK_X 3
#define XBOX_RSTICK_Y 4
#define XBOX_RTRIGGER 5
#define XBOX_DPAD_X 6
#define XBOX_DPAD_Y 7